//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkarusService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/IkarusService.WCF")]
    public partial class User : object
    {
        
        private string AdField;
        
        private System.Nullable<int> BagliOlduguBirimIdField;
        
        private string BirimAdField;
        
        private string BirimHiyerarsiField;
        
        private System.Nullable<int> BirimIdField;
        
        private System.Nullable<int> BirimYonetimSeviyesiField;
        
        private string BirimYonetimSeviyesiDescriptioniField;
        
        private System.Nullable<int> CalisanYonetimSeviyesiField;
        
        private string CalisanYonetimSeviyesiDescriptioniField;
        
        private string EpostaField;
        
        private string KullaniciNameField;
        
        private string PersonelHiyerarsiField;
        
        private System.Nullable<int> PersonelIdField;
        
        private System.Nullable<int> SicilNoField;
        
        private System.Nullable<int> CompanyIdField;
        
        private System.Nullable<System.DateTime> SonGirisDateField;
        
        private string SurnameField;
        
        private string TitleAdField;
        
        private System.Nullable<int> TitleIdField;
        
        private System.Nullable<int> UstBirimYonetimSeviyesiField;
        
        private string UstBirimYonetimSeviyesiDescriptioniField;
        
        private string YonetimHiyerarsiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BagliOlduguBirimId
        {
            get
            {
                return this.BagliOlduguBirimIdField;
            }
            set
            {
                this.BagliOlduguBirimIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirimAd
        {
            get
            {
                return this.BirimAdField;
            }
            set
            {
                this.BirimAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirimHiyerarsi
        {
            get
            {
                return this.BirimHiyerarsiField;
            }
            set
            {
                this.BirimHiyerarsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BirimId
        {
            get
            {
                return this.BirimIdField;
            }
            set
            {
                this.BirimIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BirimYonetimSeviyesi
        {
            get
            {
                return this.BirimYonetimSeviyesiField;
            }
            set
            {
                this.BirimYonetimSeviyesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirimYonetimSeviyesiDescriptioni
        {
            get
            {
                return this.BirimYonetimSeviyesiDescriptioniField;
            }
            set
            {
                this.BirimYonetimSeviyesiDescriptioniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CalisanYonetimSeviyesi
        {
            get
            {
                return this.CalisanYonetimSeviyesiField;
            }
            set
            {
                this.CalisanYonetimSeviyesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CalisanYonetimSeviyesiDescriptioni
        {
            get
            {
                return this.CalisanYonetimSeviyesiDescriptioniField;
            }
            set
            {
                this.CalisanYonetimSeviyesiDescriptioniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Eposta
        {
            get
            {
                return this.EpostaField;
            }
            set
            {
                this.EpostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciName
        {
            get
            {
                return this.KullaniciNameField;
            }
            set
            {
                this.KullaniciNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonelHiyerarsi
        {
            get
            {
                return this.PersonelHiyerarsiField;
            }
            set
            {
                this.PersonelHiyerarsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PersonelId
        {
            get
            {
                return this.PersonelIdField;
            }
            set
            {
                this.PersonelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SicilNo
        {
            get
            {
                return this.SicilNoField;
            }
            set
            {
                this.SicilNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SonGirisDate
        {
            get
            {
                return this.SonGirisDateField;
            }
            set
            {
                this.SonGirisDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleAd
        {
            get
            {
                return this.TitleAdField;
            }
            set
            {
                this.TitleAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TitleId
        {
            get
            {
                return this.TitleIdField;
            }
            set
            {
                this.TitleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UstBirimYonetimSeviyesi
        {
            get
            {
                return this.UstBirimYonetimSeviyesiField;
            }
            set
            {
                this.UstBirimYonetimSeviyesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UstBirimYonetimSeviyesiDescriptioni
        {
            get
            {
                return this.UstBirimYonetimSeviyesiDescriptioniField;
            }
            set
            {
                this.UstBirimYonetimSeviyesiDescriptioniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YonetimHiyerarsi
        {
            get
            {
                return this.YonetimHiyerarsiField;
            }
            set
            {
                this.YonetimHiyerarsiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personel", Namespace="http://schemas.datacontract.org/2004/07/IkarusService.WCF")]
    public partial class Personel : object
    {
        
        private string AdField;
        
        private string AnaNameField;
        
        private string BabaNameField;
        
        private string BirimAdField;
        
        private System.Nullable<int> BirimIdField;
        
        private string CepPhoneuSahsiField;
        
        private bool StartIstegiField;
        
        private string CinsiyetField;
        
        private int CocukCountsiField;
        
        private System.Nullable<System.DateTime> DogumDateField;
        
        private string DogumYeriField;
        
        private string EsNameSurnameiField;
        
        private string EvAddressiField;
        
        private string EvPhoneuField;
        
        private System.Nullable<System.DateTime> IlkGirisDateField;
        
        private string KadroField;
        
        private string KanGrubuField;
        
        private string LokasyonAdField;
        
        private string MedeniHaliField;
        
        private string OgrenimStatusuField;
        
        private System.Nullable<bool> OzurluKadrosundaField;
        
        private System.Nullable<int> PersonelIdField;
        
        private string SaglikStatusuField;
        
        private System.Nullable<System.DateTime> SendikaUyelikDateField;
        
        private System.Nullable<int> SicilNoField;
        
        private string CompanyNameField;
        
        private System.Nullable<int> CompanyIdField;
        
        private System.Nullable<System.DateTime> SonGirisDateField;
        
        private string SurnameField;
        
        private string TCKimlikNoField;
        
        private string TitleAdField;
        
        private System.Nullable<int> TitleIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnaName
        {
            get
            {
                return this.AnaNameField;
            }
            set
            {
                this.AnaNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaName
        {
            get
            {
                return this.BabaNameField;
            }
            set
            {
                this.BabaNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirimAd
        {
            get
            {
                return this.BirimAdField;
            }
            set
            {
                this.BirimAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BirimId
        {
            get
            {
                return this.BirimIdField;
            }
            set
            {
                this.BirimIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CepPhoneuSahsi
        {
            get
            {
                return this.CepPhoneuSahsiField;
            }
            set
            {
                this.CepPhoneuSahsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StartIstegi
        {
            get
            {
                return this.StartIstegiField;
            }
            set
            {
                this.StartIstegiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CocukCountsi
        {
            get
            {
                return this.CocukCountsiField;
            }
            set
            {
                this.CocukCountsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DogumDate
        {
            get
            {
                return this.DogumDateField;
            }
            set
            {
                this.DogumDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYeri
        {
            get
            {
                return this.DogumYeriField;
            }
            set
            {
                this.DogumYeriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsNameSurnamei
        {
            get
            {
                return this.EsNameSurnameiField;
            }
            set
            {
                this.EsNameSurnameiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EvAddressi
        {
            get
            {
                return this.EvAddressiField;
            }
            set
            {
                this.EvAddressiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EvPhoneu
        {
            get
            {
                return this.EvPhoneuField;
            }
            set
            {
                this.EvPhoneuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IlkGirisDate
        {
            get
            {
                return this.IlkGirisDateField;
            }
            set
            {
                this.IlkGirisDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kadro
        {
            get
            {
                return this.KadroField;
            }
            set
            {
                this.KadroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KanGrubu
        {
            get
            {
                return this.KanGrubuField;
            }
            set
            {
                this.KanGrubuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LokasyonAd
        {
            get
            {
                return this.LokasyonAdField;
            }
            set
            {
                this.LokasyonAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedeniHali
        {
            get
            {
                return this.MedeniHaliField;
            }
            set
            {
                this.MedeniHaliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgrenimStatusu
        {
            get
            {
                return this.OgrenimStatusuField;
            }
            set
            {
                this.OgrenimStatusuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> OzurluKadrosunda
        {
            get
            {
                return this.OzurluKadrosundaField;
            }
            set
            {
                this.OzurluKadrosundaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PersonelId
        {
            get
            {
                return this.PersonelIdField;
            }
            set
            {
                this.PersonelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaglikStatusu
        {
            get
            {
                return this.SaglikStatusuField;
            }
            set
            {
                this.SaglikStatusuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SendikaUyelikDate
        {
            get
            {
                return this.SendikaUyelikDateField;
            }
            set
            {
                this.SendikaUyelikDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SicilNo
        {
            get
            {
                return this.SicilNoField;
            }
            set
            {
                this.SicilNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SonGirisDate
        {
            get
            {
                return this.SonGirisDateField;
            }
            set
            {
                this.SonGirisDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCKimlikNo
        {
            get
            {
                return this.TCKimlikNoField;
            }
            set
            {
                this.TCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleAd
        {
            get
            {
                return this.TitleAdField;
            }
            set
            {
                this.TitleAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TitleId
        {
            get
            {
                return this.TitleIdField;
            }
            set
            {
                this.TitleIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://schemas.datacontract.org/2004/07/IkarusService.WCF")]
    public partial class Company : object
    {
        
        private int IdField;
        
        private string CompanyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaviYakaPersonel", Namespace="http://schemas.datacontract.org/2004/07/IkarusService.WCF")]
    public partial class MaviYakaPersonel : object
    {
        
        private string AdField;
        
        private bool StartIstegiField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private string CinsiyetField;
        
        private int CocukCountsiField;
        
        private int DisiplinCurrencyulu1SeneOnceField;
        
        private int DisiplinCurrencyulu2SeneOnceField;
        
        private int DisiplinCurrencyulu3SeneOnceField;
        
        private int DisiplinCurrencyuluCountsiField;
        
        private System.Nullable<System.DateTime> DogumDateField;
        
        private string EkipLideriNameField;
        
        private int FMKatilmamaDiger1SeneOnceField;
        
        private int FMKatilmamaDiger2SeneOnceField;
        
        private int FMKatilmamaDiger3SeneOnceField;
        
        private int FMKatilmamaDigerCountsiField;
        
        private int IcraCountsiField;
        
        private int Ihtar1SeneOnceField;
        
        private int Ihtar2SeneOnceField;
        
        private int Ihtar3SeneOnceField;
        
        private int IhtarCountsiField;
        
        private System.Nullable<System.DateTime> IlkGirisDateField;
        
        private decimal IstirahatGunField;
        
        private string KadroField;
        
        private string MedeniHaliField;
        
        private decimal NamezunGunField;
        
        private string OgrenimStatusuField;
        
        private System.Nullable<int> PersonelIdField;
        
        private string SaglikStatusuField;
        
        private System.Nullable<System.DateTime> SendikaUyelikDateField;
        
        private System.Nullable<int> SicilNoField;
        
        private string CompanyNameField;
        
        private System.Nullable<int> CompanyIdField;
        
        private System.Nullable<System.DateTime> SonGirisDateField;
        
        private string SurnameField;
        
        private int SozluUyari1SeneOnceField;
        
        private int SozluUyari2SeneOnceField;
        
        private int SozluUyari3SeneOnceField;
        
        private int SozluUyariCountsiField;
        
        private decimal ToplamIcraBorcuField;
        
        private int Tutanak1SeneOnceField;
        
        private int Tutanak2SeneOnceField;
        
        private int Tutanak3SeneOnceField;
        
        private int TutanakCountsiField;
        
        private decimal UcretsizIzinField;
        
        private string TitleAdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StartIstegi
        {
            get
            {
                return this.StartIstegiField;
            }
            set
            {
                this.StartIstegiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CocukCountsi
        {
            get
            {
                return this.CocukCountsiField;
            }
            set
            {
                this.CocukCountsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisiplinCurrencyulu1SeneOnce
        {
            get
            {
                return this.DisiplinCurrencyulu1SeneOnceField;
            }
            set
            {
                this.DisiplinCurrencyulu1SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisiplinCurrencyulu2SeneOnce
        {
            get
            {
                return this.DisiplinCurrencyulu2SeneOnceField;
            }
            set
            {
                this.DisiplinCurrencyulu2SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisiplinCurrencyulu3SeneOnce
        {
            get
            {
                return this.DisiplinCurrencyulu3SeneOnceField;
            }
            set
            {
                this.DisiplinCurrencyulu3SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisiplinCurrencyuluCountsi
        {
            get
            {
                return this.DisiplinCurrencyuluCountsiField;
            }
            set
            {
                this.DisiplinCurrencyuluCountsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DogumDate
        {
            get
            {
                return this.DogumDateField;
            }
            set
            {
                this.DogumDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EkipLideriName
        {
            get
            {
                return this.EkipLideriNameField;
            }
            set
            {
                this.EkipLideriNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FMKatilmamaDiger1SeneOnce
        {
            get
            {
                return this.FMKatilmamaDiger1SeneOnceField;
            }
            set
            {
                this.FMKatilmamaDiger1SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FMKatilmamaDiger2SeneOnce
        {
            get
            {
                return this.FMKatilmamaDiger2SeneOnceField;
            }
            set
            {
                this.FMKatilmamaDiger2SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FMKatilmamaDiger3SeneOnce
        {
            get
            {
                return this.FMKatilmamaDiger3SeneOnceField;
            }
            set
            {
                this.FMKatilmamaDiger3SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FMKatilmamaDigerCountsi
        {
            get
            {
                return this.FMKatilmamaDigerCountsiField;
            }
            set
            {
                this.FMKatilmamaDigerCountsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IcraCountsi
        {
            get
            {
                return this.IcraCountsiField;
            }
            set
            {
                this.IcraCountsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ihtar1SeneOnce
        {
            get
            {
                return this.Ihtar1SeneOnceField;
            }
            set
            {
                this.Ihtar1SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ihtar2SeneOnce
        {
            get
            {
                return this.Ihtar2SeneOnceField;
            }
            set
            {
                this.Ihtar2SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ihtar3SeneOnce
        {
            get
            {
                return this.Ihtar3SeneOnceField;
            }
            set
            {
                this.Ihtar3SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IhtarCountsi
        {
            get
            {
                return this.IhtarCountsiField;
            }
            set
            {
                this.IhtarCountsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IlkGirisDate
        {
            get
            {
                return this.IlkGirisDateField;
            }
            set
            {
                this.IlkGirisDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IstirahatGun
        {
            get
            {
                return this.IstirahatGunField;
            }
            set
            {
                this.IstirahatGunField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kadro
        {
            get
            {
                return this.KadroField;
            }
            set
            {
                this.KadroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedeniHali
        {
            get
            {
                return this.MedeniHaliField;
            }
            set
            {
                this.MedeniHaliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NamezunGun
        {
            get
            {
                return this.NamezunGunField;
            }
            set
            {
                this.NamezunGunField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgrenimStatusu
        {
            get
            {
                return this.OgrenimStatusuField;
            }
            set
            {
                this.OgrenimStatusuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PersonelId
        {
            get
            {
                return this.PersonelIdField;
            }
            set
            {
                this.PersonelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaglikStatusu
        {
            get
            {
                return this.SaglikStatusuField;
            }
            set
            {
                this.SaglikStatusuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SendikaUyelikDate
        {
            get
            {
                return this.SendikaUyelikDateField;
            }
            set
            {
                this.SendikaUyelikDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SicilNo
        {
            get
            {
                return this.SicilNoField;
            }
            set
            {
                this.SicilNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SonGirisDate
        {
            get
            {
                return this.SonGirisDateField;
            }
            set
            {
                this.SonGirisDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SozluUyari1SeneOnce
        {
            get
            {
                return this.SozluUyari1SeneOnceField;
            }
            set
            {
                this.SozluUyari1SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SozluUyari2SeneOnce
        {
            get
            {
                return this.SozluUyari2SeneOnceField;
            }
            set
            {
                this.SozluUyari2SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SozluUyari3SeneOnce
        {
            get
            {
                return this.SozluUyari3SeneOnceField;
            }
            set
            {
                this.SozluUyari3SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SozluUyariCountsi
        {
            get
            {
                return this.SozluUyariCountsiField;
            }
            set
            {
                this.SozluUyariCountsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ToplamIcraBorcu
        {
            get
            {
                return this.ToplamIcraBorcuField;
            }
            set
            {
                this.ToplamIcraBorcuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tutanak1SeneOnce
        {
            get
            {
                return this.Tutanak1SeneOnceField;
            }
            set
            {
                this.Tutanak1SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tutanak2SeneOnce
        {
            get
            {
                return this.Tutanak2SeneOnceField;
            }
            set
            {
                this.Tutanak2SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tutanak3SeneOnce
        {
            get
            {
                return this.Tutanak3SeneOnceField;
            }
            set
            {
                this.Tutanak3SeneOnceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TutanakCountsi
        {
            get
            {
                return this.TutanakCountsiField;
            }
            set
            {
                this.TutanakCountsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UcretsizIzin
        {
            get
            {
                return this.UcretsizIzinField;
            }
            set
            {
                this.UcretsizIzinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleAd
        {
            get
            {
                return this.TitleAdField;
            }
            set
            {
                this.TitleAdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vEkipKalemi", Namespace="http://schemas.datacontract.org/2004/07/IkarusService.WCF")]
    public partial class vEkipKalemi : object
    {
        
        private int EkipIdField;
        
        private string EkipLideriAdSurnameField;
        
        private int EkipLideriPersonelIdField;
        
        private string PersonelAdSurnameField;
        
        private int PersonelIdField;
        
        private int SicilNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EkipId
        {
            get
            {
                return this.EkipIdField;
            }
            set
            {
                this.EkipIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EkipLideriAdSurname
        {
            get
            {
                return this.EkipLideriAdSurnameField;
            }
            set
            {
                this.EkipLideriAdSurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EkipLideriPersonelId
        {
            get
            {
                return this.EkipLideriPersonelIdField;
            }
            set
            {
                this.EkipLideriPersonelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonelAdSurname
        {
            get
            {
                return this.PersonelAdSurnameField;
            }
            set
            {
                this.PersonelAdSurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonelId
        {
            get
            {
                return this.PersonelIdField;
            }
            set
            {
                this.PersonelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SicilNo
        {
            get
            {
                return this.SicilNoField;
            }
            set
            {
                this.SicilNoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IkarusService.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserByUserName", ReplyAction="http://tempuri.org/IService/GetUserByUserNameResponse")]
        System.Threading.Tasks.Task<IkarusService.User> GetUserByUserNameAsync(string kullaniciName, int istenStartYili);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserByPersonelId", ReplyAction="http://tempuri.org/IService/GetUserByPersonelIdResponse")]
        System.Threading.Tasks.Task<IkarusService.User> GetUserByPersonelIdAsync(int personelId, int istenStartYili);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<IkarusService.User[]> GetAllUsersAsync(int sirketId, int istenStartYili);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPersonnelByPersonelId", ReplyAction="http://tempuri.org/IService/GetPersonnelByPersonelIdResponse")]
        System.Threading.Tasks.Task<IkarusService.Personel> GetPersonnelByPersonelIdAsync(int personelId, int istenStartYili);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllPersonnels", ReplyAction="http://tempuri.org/IService/GetAllPersonnelsResponse")]
        System.Threading.Tasks.Task<IkarusService.Personel[]> GetAllPersonnelsAsync(int sirketId, int istenStartYili);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllCompany", ReplyAction="http://tempuri.org/IService/GetAllCompanyResponse")]
        System.Threading.Tasks.Task<IkarusService.Company[]> GetAllCompanyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllActiveBlueCollarStaffForCompany", ReplyAction="http://tempuri.org/IService/GetAllActiveBlueCollarStaffForCompanyResponse")]
        System.Threading.Tasks.Task<IkarusService.MaviYakaPersonel[]> GetAllActiveBlueCollarStaffForCompanyAsync(int yil, int ay, int sirketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTeamLeaders", ReplyAction="http://tempuri.org/IService/GetTeamLeadersResponse")]
        System.Threading.Tasks.Task<IkarusService.vEkipKalemi[]> GetTeamLeadersAsync(int personelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllBlueCollarStaffOnlyName", ReplyAction="http://tempuri.org/IService/GetAllBlueCollarStaffOnlyNameResponse")]
        System.Threading.Tasks.Task<IkarusService.MaviYakaPersonel[]> GetAllBlueCollarStaffOnlyNameAsync(int sirketId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IServiceChannel : IkarusService.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<IkarusService.IService>, IkarusService.IService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<IkarusService.User> GetUserByUserNameAsync(string kullaniciName, int istenStartYili)
        {
            return base.Channel.GetUserByUserNameAsync(kullaniciName, istenStartYili);
        }
        
        public System.Threading.Tasks.Task<IkarusService.User> GetUserByPersonelIdAsync(int personelId, int istenStartYili)
        {
            return base.Channel.GetUserByPersonelIdAsync(personelId, istenStartYili);
        }
        
        public System.Threading.Tasks.Task<IkarusService.User[]> GetAllUsersAsync(int sirketId, int istenStartYili)
        {
            return base.Channel.GetAllUsersAsync(sirketId, istenStartYili);
        }
        
        public System.Threading.Tasks.Task<IkarusService.Personel> GetPersonnelByPersonelIdAsync(int personelId, int istenStartYili)
        {
            return base.Channel.GetPersonnelByPersonelIdAsync(personelId, istenStartYili);
        }
        
        public System.Threading.Tasks.Task<IkarusService.Personel[]> GetAllPersonnelsAsync(int sirketId, int istenStartYili)
        {
            return base.Channel.GetAllPersonnelsAsync(sirketId, istenStartYili);
        }
        
        public System.Threading.Tasks.Task<IkarusService.Company[]> GetAllCompanyAsync()
        {
            return base.Channel.GetAllCompanyAsync();
        }
        
        public System.Threading.Tasks.Task<IkarusService.MaviYakaPersonel[]> GetAllActiveBlueCollarStaffForCompanyAsync(int yil, int ay, int sirketId)
        {
            return base.Channel.GetAllActiveBlueCollarStaffForCompanyAsync(yil, ay, sirketId);
        }
        
        public System.Threading.Tasks.Task<IkarusService.vEkipKalemi[]> GetTeamLeadersAsync(int personelId)
        {
            return base.Channel.GetTeamLeadersAsync(personelId);
        }
        
        public System.Threading.Tasks.Task<IkarusService.MaviYakaPersonel[]> GetAllBlueCollarStaffOnlyNameAsync(int sirketId)
        {
            return base.Channel.GetAllBlueCollarStaffOnlyNameAsync(sirketId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://sarpapp02.sarp.network:30000/IkarusService.WCF.Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
